"""
IESO LMP Proxy Server
Serves index.html and proxies requests to IESO report sites,
bypassing browser CORS restrictions.

Endpoints:
  GET  /               — Serves index.html
  GET  /fetch-csv      — Proxies public CSV reports (no auth)
  POST /fetch-private  — Proxies private XML reports (HTTP Basic Auth via config.py)

Usage:
    pip install flask requests
    python server.py

Access via Tailscale at: http://<tailscale-ip>:5000
"""

import requests
from flask import Flask, request, Response, send_from_directory
import os

app = Flask(__name__, static_folder=".")

# Whitelisted base URLs for public CSV reports
ALLOWED_PUBLIC_URLS = [
    "https://reports-public.ieso.ca/public/DAHourlyEnergyLMP/",
    "https://reports-public.ieso.ca/public/PredispHourlyEnergyLMP/",
]

# Whitelisted base URL for private reports
ALLOWED_PRIVATE_BASE = "https://reports.ieso.ca/api/v2.0/files/private/"

# Create ./data folder next to server.py on startup
DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")
os.makedirs(DATA_DIR, exist_ok=True)

# Load credentials from config.py (generated by install.bat, excluded from GitHub)
try:
    import config
    IESO_USERNAME = config.IESO_USERNAME
    IESO_PASSWORD = config.IESO_PASSWORD
    print("[OK] Loaded IESO credentials from config.py")
except ImportError:
    IESO_USERNAME = None
    IESO_PASSWORD = None
    print("[WARN] config.py not found — private report fetching will be unavailable.")
    print("       Run install.bat to set up credentials.")


@app.route("/")
def index():
    """Serve the main HTML file."""
    return send_from_directory(".", "index.html")


@app.route("/fetch-csv")
def fetch_csv():
    """
    Proxy endpoint for public IESO CSV files.
    Query param: url=<full ieso csv url>
    - Validates against public URL whitelist
    - Fetches from IESO
    - Saves to ./data/<filename>.csv
    - Returns CSV content to browser
    """
    url = request.args.get("url")

    if not url:
        return Response("Missing 'url' parameter.", status=400)

    if not any(url.startswith(base) for base in ALLOWED_PUBLIC_URLS):
        return Response("URL not allowed.", status=403)

    try:
        ieso_response = requests.get(url, timeout=15)
        ieso_response.raise_for_status()
    except requests.exceptions.HTTPError as e:
        return Response(f"IESO returned error: {e}", status=502)
    except requests.exceptions.RequestException as e:
        return Response(f"Failed to fetch from IESO: {e}", status=502)

    filename  = url.split("/")[-1]
    save_path = os.path.join(DATA_DIR, filename)
    with open(save_path, "wb") as f:
        f.write(ieso_response.content)
    print(f"[saved] {save_path}")

    return Response(
        ieso_response.content,
        status=200,
        mimetype="text/csv",
        headers={"Access-Control-Allow-Origin": "*"},
    )


@app.route("/fetch-private", methods=["POST"])
def fetch_private():
    """
    Authenticated proxy endpoint for IESO confidential reports.
    Expects JSON body: { "url": "..." }
    Credentials are loaded from config.py — never sent from the browser.
    - Validates URL against private whitelist
    - Performs HTTP Basic Auth against IESO using config.py credentials
    - Saves XML to ./data/<filename>
    - Returns XML content to browser
    """
    if not IESO_USERNAME or not IESO_PASSWORD:
        return Response(
            "IESO credentials not configured. Run install.bat to set up config.py.",
            status=503
        )

    data = request.get_json(silent=True)
    if not data:
        return Response("Missing JSON body.", status=400)

    url = data.get("url", "").strip()
    if not url:
        return Response("Missing url.", status=400)

    if not url.startswith(ALLOWED_PRIVATE_BASE):
        return Response("URL not allowed.", status=403)

    try:
        ieso_response = requests.get(url, auth=(IESO_USERNAME, IESO_PASSWORD), timeout=15)
        ieso_response.raise_for_status()
    except requests.exceptions.HTTPError as e:
        return Response(f"IESO returned error: {e}", status=502)
    except requests.exceptions.RequestException as e:
        return Response(f"Failed to fetch from IESO: {e}", status=502)

    filename  = url.split("?")[0].split("/")[-1]
    save_path = os.path.join(DATA_DIR, filename)
    with open(save_path, "wb") as f:
        f.write(ieso_response.content)
    print(f"[saved] {save_path}")

    return Response(
        ieso_response.content,
        status=200,
        mimetype="application/xml",
        headers={"Access-Control-Allow-Origin": "*"},
    )


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=False)
